# Generated by Django 4.2.5 on 2023-09-18 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eSangrah', '0003_offers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Offers',
            new_name='Offer',
        ),
    ]
