# Generated by Django 4.2.5 on 2023-09-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eSangrah', '0005_fruit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electronic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='fruits_img')),
                ('desc', models.CharField(max_length=100)),
                ('price', models.FloatField(max_length=6)),
            ],
        ),
    ]
