# Generated by Django 4.2.5 on 2023-09-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eSangrah', '0006_electronic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=13)),
                ('desc', models.TextField()),
                ('file', models.FileField(upload_to='')),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
