# Generated by Django 4.2.5 on 2023-09-25 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eSangrah', '0007_prints'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prints',
            new_name='Xerox',
        ),
    ]
