# Generated by Django 4.2.5 on 2023-09-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eSangrah', '0008_rename_prints_xerox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xerox',
            name='file',
            field=models.FileField(null=True, upload_to='documents/%Y/%m/%d'),
        ),
    ]
