# Generated by Django 4.1.7 on 2023-09-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eSangrah', '0012_dailyneed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyneed',
            name='image',
            field=models.ImageField(upload_to='dailyneed_img'),
        ),
    ]
