# Generated by Django 4.2.5 on 2023-09-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eSangrah', '0014_stationary_alter_electronic_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationary',
            name='longdesc',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stationary',
            name='desc',
            field=models.CharField(max_length=20),
        ),
    ]
