# Generated by Django 4.2.5 on 2023-09-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eSangrah', '0015_stationary_longdesc_alter_stationary_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stationary',
            name='longdesc',
        ),
        migrations.AddField(
            model_name='product',
            name='longdesc',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
