# Generated by Django 4.2.5 on 2023-09-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eSangrah', '0016_remove_stationary_longdesc_product_longdesc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='longdesc',
            field=models.CharField(max_length=300),
        ),
    ]
