# Generated by Django 4.2.5 on 2023-09-29 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eSangrah', '0018_product_image2_product_image3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image2',
            new_name='image_2',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image3',
            new_name='image_3',
        ),
    ]
