# Generated by Django 4.2.5 on 2023-09-29 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eSangrah', '0019_rename_image2_product_image_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_3',
        ),
    ]
